name: Build Beta APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        working-directory: android
        run: chmod +x gradlew

      - name: Build Beta APK
        working-directory: android
        run: ./gradlew assembleBeta --stacktrace

      - name: Upload Beta APK
        uses: actions/upload-artifact@v4
        with:
          name: StreamDek-Beta-APK
          path: android/**/build/outputs/apk/beta/*.apk
